### ISSUE TITLE
Full arduino code?

### ISSUE THREAD

**Issue by AnykeyNL** [whitebird/fri3d-eyes#3]
Ziet er geweldig uit! Is er al info om de gehele arduino code, niet alleen wat in de loop staat?

**Comment by DrSkunk** [comment]
Goed idee, zal ik toevoegen!

**Comment by DrSkunk** [comment]
Toegevoegd! https://github.com/whitebird/fri3d-eyes/commit/16fa7333f8ddf229251e6922c5f34a6bc093c8d9
